// npm manifests reviewed 2026-10-08. Candidates, not security certification.
export const piPluginCatalog = [
  {
    name: "pi-web-access",
    version: "0.37.0",
    category: "联网与检索",
    description: "网页、PDF 与视频检索",
    risk: "部分服务需要 API Key，内容会发送给所选服务。",
    repository: "https://github.com/nicobailon/pi-web-access",
    license: "MIT",
    peers: {
      typebox: "*",
      "@earendil-works/pi-ai": "*",
      "@earendil-works/pi-tui": "*",
      "@earendil-works/pi-coding-agent": "*",
    },
  },
  {
    name: "pi-subagents",
    version: "0.76.1",
    category: "任务协作",
    description: "子代理委派与工作流",
    risk: "会增加模型费用；子代理可执行本地工具。",
    repository: "https://github.com/nicobailon/pi-subagents",
    license: "MIT",
    peers: {
      typebox: "*",
      "@earendil-works/pi-ai": ">=0.86.1",
      "@earendil-works/pi-tui": "*",
      "@earendil-works/pi-agent-core": "*",
      "@earendil-works/pi-coding-agent": "*",
    },
  },
  {
    name: "pi-powerline-footer",
    version: "0.19.1",
    category: "界面体验",
    description: "紧凑的状态栏与会话信息",
    risk: "改变终端显示；请检查当前 Pi 版本。",
    repository: "https://github.com/nicobailon/pi-powerline-footer",
    license: "MIT",
    peers: {
      "@earendil-works/pi-ai": ">=0.81.0",
      "@earendil-works/pi-tui": ">=0.81.0",
      "@earendil-works/pi-coding-agent": ">=0.81.0",
    },
  },
  {
    name: "@plannotator/pi-extension",
    version: "0.28.8",
    category: "代码质量",
    description: "计划与代码审阅批注",
    risk: "会启动本地审阅界面。",
    repository: "https://github.com/backnotprop/plannotator",
    license: "MIT OR Apache-2.0",
    peers: {
      "@earendil-works/pi-coding-agent": ">=0.79.1",
    },
  },
  {
    name: "@narumitw/pi-usage",
    version: "0.64.1",
    category: "用量管理",
    description: "查看账户配额与用量",
    risk: "可能访问供应商用量接口及本地凭据。",
    repository: "https://github.com/narumiruna/pi-extensions",
    license: "MIT",
    peers: {
      "@earendil-works/pi-ai": "*",
      "@earendil-works/pi-tui": "*",
      "@earendil-works/pi-coding-agent": "*",
    },
  },
  {
    name: "pi-memory",
    version: "0.4.2",
    category: "上下文管理",
    description: "跨会话记忆与语义检索",
    risk: "语义检索需额外配置 qmd；留意存储的代码与隐私。",
    repository: "https://github.com/jayzeng/pi-memory",
    license: "MIT",
    peers: {
      "@earendil-works/pi-ai": ">=0.81.1",
      "@earendil-works/pi-coding-agent": ">=0.81.1",
    },
  },
  {
    name: "pi-prompt-template-model",
    version: "0.12.3",
    category: "工作流",
    description: "按提示模板指定模型",
    risk: "需配置可用模型，可能产生额外费用。",
    repository: "https://github.com/nicobailon/pi-prompt-template-model",
    license: "MIT",
    peers: {
      typebox: "*",
      "@earendil-works/pi-ai": "*",
      "@earendil-works/pi-tui": "*",
      "@earendil-works/pi-agent-core": "*",
      "@earendil-works/pi-coding-agent": "*",
    },
  },
  {
    name: "@langfuse/pi-observability-plugin",
    version: "0.1.2",
    category: "可观测性",
    description: "会话追踪与调用分析",
    risk: "需要 Langfuse 配置；可能上传提示与响应，含外部数据传输。",
    repository: "https://github.com/langfuse/pi-observability-plugin",
    license: "MIT",
    peers: {
      "@earendil-works/pi-coding-agent": "*",
    },
  },
  {
    name: "pi-cache-optimizer",
    version: "2.8.21",
    category: "用量管理",
    description: "优化提示缓存与上下文使用",
    risk: "会调整上下文行为，成本与效果取决于模型。",
    repository: "https://github.com/jiangge/pi-cache-optimizer",
    license: "MIT",
    peers: {
      "@earendil-works/pi-coding-agent": ">=0.82.0",
    },
  },
  {
    name: "pi-simplify",
    version: "0.2.3",
    category: "代码质量",
    description: "检查并简化变更中的代码",
    risk: "有旧 TypeBox peer 依赖；建议先在隔离环境检查兼容性。",
    repository: "https://github.com/MattDevy/pi-extensions",
    license: "MIT",
    peers: {
      "@sinclair/typebox": "^0.34.0",
      "@earendil-works/pi-ai": ">=0.74.0",
      "@earendil-works/pi-tui": ">=0.74.0",
      "@earendil-works/pi-coding-agent": ">=0.74.0",
    },
  },
] as const;
